name: Collect Test status

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    uses: sketchylizard/ActionsTest/.github/workflows/01-cmake.yml@main

  run_tests:
    # The type of runner that the job will run on
    runs-on: [ self-hosted ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Executing tests
        run: python3 ${{github.workspace}}/Tools/RunTests.py ${{github.workspace}}/build/tests
